# -*- coding: utf-8 -*-
"""TableFile.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rz1bcfxgw0WBU0RexUXCyjP_CYHI9F7w

**INSTALLATION**
"""

!pip install -q transformers==4.4.2

# import torch
torch.__version__

!pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-2.1.0+cu118.html
!pip install -q -U trl transformers accelerate git+https://github.com/huggingface/peft.git
!pip install -q datasets bitsandbytes einops wandb

from transformers import pipeline
import pandas as pd

"""**LOAD THE** **DATASET**"""

#Load a dataset
from datasets import load_dataset

dataset_name = 'inria-soda/tabular-benchmark' #french novels
config_name = 'clf_cat_road-safety'
dataset = load_dataset(dataset_name, config_name, split="train")

"""**Train the model**"""

# train the model
tqa = pipeline(task="table-question-answering",
               model="google/tapas-base-finetuned-wtq")

# trainer.train()

table = pd.read_csv("data.csv")
table = table.astype(str)

table

query = "Who has scored the highest runs?"
print(tqa(table=table, query=query)["answer"])

query = ["Virat Kohli's highest score?", "Which team does he play for?"]
answer = tqa(table=table, query=query)

for ans in answer:
    if "AVERAGE" in ans["answer"]:
        average_score = ans["answer"].split(">")[1].strip()
        print(average_score)
    else:
        print(ans["answer"])